### ISSUE TITLE
Is there a way to make use of the referencing mongoose offers?

### ISSUE THREAD

**Issue by mahulst** [MartyIce/generator-angular-fullstack-crud#1]
In the config you make use of "ManualReference." Then in the frontend code you manually match the guest_id property of the Reservation to the _id of the Guest. 

Mongoose has it's own way to reference other Models, is there a way to use that with this generator?

**Comment by MartyIce** [comment]
That is not currently supported by this generator, but should be easy enough to add.  If you could direct me to some documentation/samples, I can take a look.  I don't know when I'll be able to get to it, though - if you feel like taking a stab at it, I take pull requests!  Thanks.
