### ISSUE TITLE
Doesn't work with the new angular-fullstack-generator

### ISSUE THREAD

**Issue by manuelwallrapp** [MartyIce/generator-angular-fullstack-crud#3]
I was so amazed to see there is a crud generator. But sadly it doesn't work with the actual angular-fullstack version. Is there an update planned?

**Comment by MartyIce** [comment]
Thank you for the heads up - I had pushed a working version to github, but hadn't published the update to npm.  Just did so (version 0.0.2), ran a test, and it works.  Make sure to update the appName in the config json, that tripped me up several times testing :)
